dataset_name: 'replica'
# meshing:
#   eval_rec: True
# tracking:
#   vis_freq: 50
#   vis_inside_freq: 25
#   ignore_edge_W: 100
#   ignore_edge_H: 100
#   seperate_LR: False
#   const_speed_assumption: True
#   lr: 0.001
#   pixels: 200
#   iters: 10
# mapping:
#   every_frame: 5
#   vis_freq: 50
#   vis_inside_freq: 30
#   mesh_freq: 50
#   ckpt_freq: 500
#   keyframe_every: 50
#   mapping_window_size: 5
#   pixels: 1000
#   iters_first: 1500
#   iters: 60
camera_params:
  image_height: 480
  image_width: 640
  fx: 372.67385545577224
  fy: 372.67385545577224
  cx: 320.0
  cy: 240.0
  png_depth_scale: 1000.0
  crop_edge: 0